"""new_migration

Revision ID: 3e9c886df0a6
Revises: 457117f4a96a
Create Date: 2025-06-09 17:37:27.800801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e9c886df0a6'
down_revision: Union[str, None] = '457117f4a96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'state',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'sqlite'),
               nullable=False)
    op.drop_column('devices', 'pin_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('pin_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('devices', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'sqlite'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
